{% set python_min = "3.10" %}
{% set name = "ixmp4" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ixmp4-{{ version }}.tar.gz
  sha256: 69e9e80f4a1c47f749404490013fa419258747f68e831d53ed3c05b2f470b965

build:
  entry_points:
    - ixmp4 = ixmp4.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=2.0,<3.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }},<3.14
    - pyjwt >=2.4.0
    - sqlalchemy-with-postgresql-psycopgbinary >=2.0.22
    - sqlalchemy-utils >=0.41.0
    - alembic >=1.12.0
    - fastapi >=0.100.0
    - httpx >=0.25.0
    - openpyxl >=3.0.9
    - pandas >=2.1.1
    - pandera >=0.24.0
    - pydantic >=2.3.0
    - python-dotenv >=1.0.1
    - typer >=0.9.0
    - toml >=0.10.2
    - psycopg >=3.1.12
    - pydantic-settings >=2.1.0
    - rich >=13.5.2
    - h2 >=3,<5
    - mypy >=1.7

test:
  imports:
    - ixmp4
  commands:
    - pip check
    - ixmp4 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://software.ece.iiasa.ac.at
  summary: a data warehouse for scenario analysis
  description: |
    The ixmp4 package is a data warehouse for high-powered scenario analysis
    in the domain of integrated assessment of climate change and energy systems modeling
  license: MIT
  license_file: LICENSE
  doc_url: http://docs.ece.iiasa.ac.at/ixmp4
  dev_url: https://github.com/iiasa/ixmp4

extra:
  recipe-maintainers:
    - glatterf42
    - meksor
    - phackstock
    - danielhuppmann
