{% set name = "ixmp4" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ixmp4-{{ version }}.tar.gz
  sha256: 426c16813ea8581037cf7929fd38b909bd706632f8020de3c5a8334e67a40a4c

build:
  entry_points:
    - ixmp4 = ixmp4.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - poetry-core >=1.2.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.10,<3.13
    - pyjwt >=2.4.0,<3.0.0
    - sqlalchemy >=2.0.25,<3.0.0
    - sqlalchemy-utils >=0.41.1,<0.42.0
    - alembic >=1.13.1,<2.0.0
    - dask-core >=2024.1.1,<2025.0.0
    - fastapi >=0.109.0,<0.110.0
    - httpx >=0.26.0,<0.27.0
    - openpyxl >=3.0.9,<4.0.0
    - pandas >=2.1.2,<2.2.0
    - pandera >=0.18.0,<0.19.0
    - pydantic >=2.5.3,<3.0.0
    - python-dotenv >=1.0.1,<2.0.0
    - requests >=2.27.1,<3.0.0
    - typer >=0.9.0,<0.10.0
    - toml >=0.10.2,<0.11.0
    - psycopg >=3.1.17,<4.0.0
    - pydantic-settings >=2.1.0,<3.0.0
    - rich >=13.7.0,<14.0.0

test:
  imports:
    - ixmp4
  commands:
    - pip check
    - ixmp4 --help
  requires:
    - pip

about:
  home: https://software.ece.iiasa.ac.at
  summary: a data warehouse for scenario analysis
  description: |
    The ixmp4 package is a data warehouse for high-powered scenario analysis
    in the domain of integrated assessment of climate change and energy systems modeling
  license: MIT
  license_file: LICENSE
  doc_url: http://docs.ece.iiasa.ac.at/ixmp4
  dev_url: https://github.com/iiasa/ixmp4

extra:
  recipe-maintainers:
    - meksor
    - phackstock
    - danielhuppmann
