{% set name = "ixmp4" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ixmp4-{{ version }}.tar.gz
  sha256: 42c96577ecc279ffb99d3670509b2f4f1aed4c5503df003f0492d3bd2e33420e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - ixmp4 = ixmp4.__main__:app

requirements:
  host:
    - python >=3.10,<3.12
    - poetry-core >=1.2.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.10,<3.12
    - pyjwt >=2.4.0,<3.0.0
    - sqlalchemy >=2.0.22,<3.0.0
    - sqlalchemy-utils >=0.41.1,<0.42.0
    - alembic >=1.12.1,<2.0.0
    - dask-core >=2023.10.1,<2024.0.0
    - fastapi >=0.104.0,<0.105.0
    - httpx >=0.25.0,<0.26.0
    - openpyxl >=3.0.9,<4.0.0
    - pandas >=2.1.2,<3.0.0
    - pandera >=0.17.0,<0.18.0
    - pydantic >=2.4.0,<3.0.0
    - pydantic-settings >=2.0.3,<3.0.0
    - python-dotenv >=1.0.0,<2.0.0
    - requests >=2.27.1,<3.0.0
    - typer >=0.9.0,<10.0.0
    - toml >=0.10.2,<0.11.0
    - psycopg >=3.1.10,<4.0.0

test:
  imports:
    - ixmp4
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://software.ece.iiasa.ac.at
  summary: a data warehouse for scenario analysis
  description: |
    The ixmp4 package is a data warehouse for high-powered scenario analysis
    in the domain of integrated assessment of climate change and energy systems modeling
  license: MIT
  license_file: LICENSE
  doc_url: http://docs.ece.iiasa.ac.at/ixmp4
  dev_url: https://github.com/iiasa/ixmp4

extra:
  recipe-maintainers:
    - meksor
    - phackstock
    - danielhuppmann
